# in _config.yml
title: "Disease Progression Modelling"
author: The Disease Progression Modelling community
#logo: images/logo.png
execute:
  execute_notebooks: "off"

exclude_patterns: [README.md, pages/notebooks/_template.ipynb, data/README.md]


repository:
  url: https://github.com/Disease-Progression-Modelling/disease-progression-modelling.github.io/

html:
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"
